JENKINS_URL = ''
USERNAME = ''
PASSWORD = ''

CURRENT_JOB = 'ci'

SUCCESS = 'SUCCESS'
FAILURE = 'FAILURE'

NO_CONNECTED_DEVICES = 'No connected devices'
DEVICE_OFFLINE = 'device offline'

FAILED_SCENARIO = '> Scenario:'